library(RMariaDB)
mydb <- RMariaDB::dbConnect(RMariaDB::MariaDB(), user='root', password='ilcm', dbname='ilcm', host="0.0.0.0",port=db_port)
rs <- RMariaDB::dbSendStatement(mydb, 'set character set "utf8"')

rs<-dbSendStatement(mydb, "Insert Ignore into ilcm.meta_date (Select distinct dataset,date from documents);")
rs<-dbSendStatement(mydb, "Insert Ignore into ilcm.meta_mde1 (Select distinct dataset,mde1 from documents);")
rs<-dbSendStatement(mydb, "Insert Ignore into ilcm.meta_mde2 (Select distinct dataset,mde2 from documents);")
rs<-dbSendStatement(mydb, "Insert Ignore into ilcm.meta_mde3 (Select distinct dataset,mde3 from documents);")
rs<-dbSendStatement(mydb, "Insert Ignore into ilcm.meta_token (Select distinct dataset,token from documents);")
rs<-dbSendStatement(mydb, "Insert Ignore into ilcm.meta_mde4 (Select distinct dataset,mde4 from documents);")
rs<-dbSendStatement(mydb, "Insert Ignore into ilcm.meta_mde5 (Select distinct dataset,mde5 from documents);")
rs<-dbSendStatement(mydb, "Insert Ignore into ilcm.meta_mde6 (Select distinct dataset,mde6 from documents);")
rs<-dbSendStatement(mydb, "Insert Ignore into ilcm.meta_mde7 (Select distinct dataset,mde7 from documents);")
rs<-dbSendStatement(mydb, "Insert Ignore into ilcm.meta_mde8 (Select distinct dataset,mde8 from documents);")
rs<-dbSendStatement(mydb, "Insert Ignore into ilcm.meta_mde9 (Select distinct dataset,mde9 from documents);")
