version: '3.2'
services:
    zoo-1:
        image: zookeeper
        restart: always
        ports:
          - "2181:2181"
        volumes:
            - ~/.iLCM/data/zoo-1:/opt/persist
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: 2181
            ZOO_LOG_DIR: /opt/persist/logs
            ZOO_DATA_LOG_DIR: /opt/persist/data
    solr-1:
        image: solr
        restart: always
        ports:
            - 8081:8081
        volumes:
            - ~/.iLCM/data/solr-1/logs:/opt/logs
            - ~/.iLCM/data/solr-1/store:/store
            - ~/.iLCM/data/solr-1/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            SOLR_PORT: 8081
            SOLR_HOME: /store/solr
            ZK_HOST: zoo-1:2181
            SOLR_LOGS_DIR: /opt/logs
            SOLR_HOST: solr-1
            SOLR_HEAP:
            SOLR_JAVA_MEM:
        depends_on:
          - zoo-1
    db:
        image: mariadb
        ports:
         - "3306:3306"
        environment:
         - MYSQL_ROOT_PASSWORD=ilcm
         - MYSQL_DATABASE=ilcm
        volumes:
#         - ~/.iLCM/data/mariadb:/var/lib/mysql#Problem, da nicht beschreibbar muss untersucht werden
         - ~/.iLCM/data/mariadb/myconfig:/myconfig
         - ~/.iLCM/data/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
         - mariadb:/var/lib/mysql
#        entrypoint:
#            - docker-entrypoint.sh
        links:
         - solr-1
#Define the volumes here in order to have foll write rights etc.
volumes:
#    - type: bind
#      name: mariadb
#      source: ~/.iLCM/data/mariadb/
    mariadb:
        driver_opts:
            type: none
            device: ~/.iLCM/data/mariadb/
            o: bind
#    solr:
#      external:
#          name: solr
#        driver_opts:
#            type: none
#            device: ./data/solr
#            o: bind
